export type Project = { slug: string; title: string; domain: string; year: string; summary: string; context: string; work: string[]; challenges: string; solution: string; result: string; skills: string[]; tools: string[]; cover: string; coverAlt: string; featured: boolean };

export const skills = [
  { title: "Support & diagnostic", description: "Identifier une panne, expliquer clairement le problème et remettre un poste en service de manière structurée." },
  { title: "Systèmes Microsoft", description: "Construire un laboratoire Windows Server, Active Directory, DNS et postes clients pour apprendre l’administration." },
  { title: "Virtualisation", description: "Préparer, migrer et valider des machines virtuelles avec Hyper-V et Proxmox VE." },
  { title: "Infrastructure terrain", description: "Appliquer la rigueur de la planification électrique, de l’électronique et de la fibre aux environnements IT." },
];

export const projects: Project[] = [
  { slug: "laboratoire-proxmox-ve", title: "Laboratoire Proxmox VE", domain: "Virtualisation", year: "2026", summary: "Déploiement d’un hyperviseur Proxmox VE, mise à niveau contrôlée et préparation de la migration de charges Windows.", context: "Construire un laboratoire plus proche des environnements de virtualisation utilisés en infrastructure, tout en conservant des preuves de retour arrière.", work: ["Installation imbriquée pour la phase d’apprentissage", "Configuration du réseau de gestion et de la connectivité", "Mise à niveau de Proxmox VE et contrôle des services", "Import et validation d’images de disques Windows"], challenges: "La virtualisation imbriquée et le démarrage UEFI ont demandé une analyse précise des ressources, du firmware et des périphériques virtuels.", solution: "Procéder par étapes courtes, conserver des points de restauration et valider noyau, stockage, réseau et services après chaque modification.", result: "Un nœud Proxmox opérationnel, mis à jour et capable d’héberger des machines Windows de laboratoire.", skills: ["Proxmox VE", "QEMU/KVM", "Réseau", "Stockage", "Diagnostic"], tools: ["Proxmox VE 9", "PowerShell", "qemu-img", "Git"], cover: "/images/project-proxmox.svg", coverAlt: "Schéma abstrait d’un nœud Proxmox et de ses machines virtuelles", featured: true },
  { slug: "active-directory-cruzlab", title: "Domaine Active Directory de laboratoire", domain: "Systèmes Microsoft", year: "2026", summary: "Installation de Windows Server, création d’un domaine, DNS, utilisateurs, groupes et modèle d’accès AGDLP.", context: "Apprendre les fondations d’un environnement d’entreprise Microsoft dans un réseau de laboratoire isolé.", work: ["Installation et préparation de Windows Server", "Promotion du premier contrôleur de domaine", "Validation des services AD DS, DNS et Netlogon", "Création d’utilisateurs, d’OU et de groupes de sécurité"], challenges: "Distinguer les rôles DNS, DHCP, domaine et groupes, puis valider chaque couche sans confondre installation et compréhension.", solution: "Documenter les choix, utiliser des noms cohérents et vérifier l’annuaire et ses services avec les outils graphiques et PowerShell.", result: "Un domaine de laboratoire fonctionnel avec résolution DNS et une première structure d’administration basée sur les groupes.", skills: ["Windows Server", "AD DS", "DNS", "PowerShell", "AGDLP"], tools: ["Windows Server 2025", "Server Manager", "Active Directory Users and Computers"], cover: "/images/project-ad.svg", coverAlt: "Schéma abstrait d’un domaine Active Directory avec utilisateurs et groupes", featured: true },
  { slug: "poste-windows-11", title: "Poste client Windows 11", domain: "Support & poste de travail", year: "2026", summary: "Installation propre d’un poste Windows 11, traitement des prérequis et préparation à l’intégration au laboratoire.", context: "Disposer d’un poste client reproductible pour les exercices de support, réseau, domaine et politiques de groupe.", work: ["Création d’une VM UEFI avec TPM virtuel", "Installation de Windows 11 Pro", "Configuration réseau statique", "Validation de la connectivité et de la résolution DNS"], challenges: "Le démarrage de l’installateur et la contrainte de mémoire ont révélé les limites du laboratoire imbriqué.", solution: "Isoler le problème, adapter temporairement les ressources, puis revenir à une configuration conforme après l’installation.", result: "Un poste Windows 11 propre, démarrable et prêt pour l’intégration aux services du laboratoire.", skills: ["Windows 11", "UEFI", "TPM", "TCP/IP", "Dépannage"], tools: ["Proxmox VE", "Windows Setup", "PowerShell"], cover: "/images/project-windows.svg", coverAlt: "Illustration abstraite d’un poste Windows 11 dans un réseau de laboratoire", featured: true },
  { slug: "raspberry-pi-services", title: "Services personnels sur Raspberry Pi", domain: "Auto-hébergement", year: "Projet personnel", summary: "Expérimentation de services Plex et Nextcloud avec accès SSH et configuration réseau.", context: "Explorer l’auto-hébergement et comprendre les bases d’un service accessible sur un réseau domestique.", work: ["Installation de services", "Configuration d’une adresse IP fixe", "Administration à distance avec SSH", "Dépannage de la connectivité"], challenges: "Maintenir des services simples malgré les limites matérielles et les contraintes du réseau domestique.", solution: "Procéder par service, documenter les paramètres et tester localement avant toute exposition réseau.", result: "Une première expérience concrète de Linux, du réseau et de l’auto-hébergement.", skills: ["Linux", "Raspberry Pi", "SSH", "Réseau"], tools: ["Raspberry Pi", "Plex", "Nextcloud"], cover: "/images/project-pi.svg", coverAlt: "Illustration abstraite d’un Raspberry Pi hébergeant des services", featured: false },
];

export const formations = [
  { title: "Planificateur-électricien CFC", institution: "Connect Groupe E", period: "2021–2023", status: "Terminée", category: "Planification", description: "Formation duale axée sur la planification, la coordination et la documentation d’installations électriques." },
  { title: "Installateur-électricien CFC", institution: "Connect Groupe E", period: "2017–2021", status: "Terminée", category: "Électricité", description: "Formation pratique et théorique en installations électriques, sécurité et exécution sur le terrain." },
  { title: "Technicien en gestion des équipements informatiques", institution: "INETE, Lisbonne", period: "2010–2013", status: "Terminée", category: "Informatique", description: "Formation technique en systèmes informatiques. L’intitulé d’équivalence suisse reste présenté avec prudence." },
];

export const experiences = [
  { period: "2024–aujourd’hui", role: "Technicien en infrastructures industrielles / planificateur-électricien", company: "Connect Groupe E", domain: "Infrastructures" },
  { period: "2023", role: "Chef de projet et planificateur-électricien", company: "RBM Électricité", domain: "Gestion de projet" },
  { period: "2017", role: "Technicien en électronique", company: "FTH Services", domain: "Électronique" },
  { period: "2015", role: "Analyste de systèmes informatiques — dépannage", company: "COOP, mission temporaire", domain: "Informatique" },
  { period: "2013", role: "Informaticien", company: "Toshiba Portugal", domain: "Informatique" },
];

export const trades = [
  { id: "support-it", title: "Support informatique", intro: "Diagnostiquer, réparer, installer et expliquer avec une approche orientée utilisateur.", skills: ["Diagnostic", "Windows", "Matériel", "Communication"], related: ["poste-windows-11", "raspberry-pi-services"] },
  { id: "infrastructure", title: "Technicien en infrastructures", intro: "Relier systèmes, réseau, documentation et rigueur opérationnelle.", skills: ["Virtualisation", "Réseau", "Linux", "Documentation"], related: ["laboratoire-proxmox-ve", "active-directory-cruzlab"] },
  { id: "planification", title: "Planificateur-électricien", intro: "Préparer, coordonner et documenter des installations techniques avec précision.", skills: ["Planification", "Coordination", "CAO", "Normes"], related: [] },
  { id: "gestion-projet", title: "Chef de projet", intro: "Structurer le travail, suivre les contraintes et faire circuler l’information entre les intervenants.", skills: ["Organisation", "Suivi", "Communication", "Documentation"], related: [] },
];

export const articles = [
  { slug: "dns-annuaire-du-reseau", title: "DNS: l’annuaire qui rend le réseau lisible", category: "Réseaux", excerpt: "Comprendre pourquoi un nom de machine doit être traduit en adresse IP et le rôle central du DNS dans Active Directory.", status: "published", reading: "4 min" },
  { slug: "powershell-outil-administration", title: "PowerShell, du terminal à l’administration", category: "Windows", excerpt: "Une introduction pratique à l’automatisation, à l’inspection et à la validation d’un environnement Windows.", status: "published", reading: "5 min" },
  { slug: "securite-electrique-suisse", title: "Sécurité électrique en Suisse", category: "Électricité", excerpt: "Brouillon en attente de validation réglementaire.", status: "draft", reading: "—" },
];
