export type PillarId = "terrain" | "planification" | "informatique";

export type Project = {
  slug: string;
  title: string;
  type: "Expérience professionnelle" | "Réalisation professionnelle" | "Projet personnel" | "Laboratoire d’apprentissage";
  domain: string;
  pillar: PillarId;
  year: string;
  summary: string;
  context: string;
  objective: string;
  role: string;
  work: string[];
  challenges: string;
  solution: string;
  result: string;
  limitations?: string;
  skills: string[];
  tools: string[];
  coverAlt: string;
  imageType: "technical-illustration";
  featured: boolean;
};

export const pillars = [
  { id: "terrain" as const, title: "Infrastructures & électricité", kicker: "Terrain", description: "Exécuter et comprendre des installations techniques avec une attention constante à la sécurité, à la qualité et aux contraintes du site.", skills: ["Infrastructures industrielles", "Installations électriques", "Fibre optique", "Diagnostic terrain"] },
  { id: "planification" as const, title: "Planification & coordination", kicker: "Du plan au chantier", description: "Préparer des plans, coordonner les intervenants et rendre les décisions techniques compréhensibles et traçables.", skills: ["AutoCAD & Revit", "Documentation", "Suivi technique", "Gestion de projet"] },
  { id: "informatique" as const, title: "Informatique & systèmes", kicker: "Diagnostic et progression", description: "Diagnostiquer du matériel et des systèmes, puis approfondir les réseaux et l’administration dans un laboratoire personnel documenté.", skills: ["Support Windows & macOS", "Windows Server", "Virtualisation", "Réseaux"] },
];

export const projects: Project[] = [
  { slug: "infrastructures-industrielles", title: "Infrastructures industrielles et installations techniques", type: "Expérience professionnelle", domain: "Infrastructures", pillar: "terrain", year: "2024–aujourd’hui", summary: "Travail technique de terrain et de planification dans des environnements d’infrastructures industrielles.", context: "Activité professionnelle actuelle chez Connect Groupe E, à l’interface entre exécution, compréhension des installations et préparation technique.", objective: "Contribuer à des installations fiables et documentées en tenant compte des contraintes du terrain.", role: "Technicien en infrastructures industrielles / planificateur-électricien.", work: ["Lecture et utilisation de documents techniques", "Prise en compte des contraintes d’installation", "Coordination entre préparation et exécution", "Contrôles et communication des informations utiles"], challenges: "Conserver une vision d’ensemble tout en traitant les détails techniques et les contraintes réelles du site.", solution: "Structurer les informations, vérifier les interfaces et communiquer de manière précise avec les intervenants.", result: "Une expérience professionnelle qui relie le terrain, la planification et la fiabilité opérationnelle.", limitations: "Les détails de sites, clients et installations restent confidentiels.", skills: ["Infrastructures", "Électricité", "Coordination", "Sécurité"], tools: ["Plans techniques", "Documentation de chantier", "Outils de mesure"], coverAlt: "Illustration technique d’une infrastructure industrielle et de sa distribution électrique", imageType: "technical-illustration", featured: true },
  { slug: "planification-electrique", title: "Planification électrique et coordination", type: "Expérience professionnelle", domain: "Planification", pillar: "planification", year: "2021–aujourd’hui", summary: "Préparation de plans et coordination technique, du besoin initial jusqu’aux informations utiles au chantier.", context: "Compétence développée pendant le CFC de planificateur-électricien, puis exercée dans des fonctions de planification et de gestion de projet.", objective: "Transformer des contraintes techniques en documents exploitables par les différents intervenants.", role: "Planificateur-électricien CFC, avec une expérience de chef de projet en 2023.", work: ["Préparation et lecture de plans", "Coordination d’informations techniques", "Suivi de points ouverts", "Lien entre la planification et l’exécution"], challenges: "Éviter les pertes d’information entre le plan, les décisions et la réalité du chantier.", solution: "Travailler avec une structure claire, des contrôles réguliers et une documentation adaptée au destinataire.", result: "Une méthode de travail transférable à tout environnement technique complexe.", limitations: "Les détails liés aux sites et aux clients ne sont pas publiés.", skills: ["Planification", "AutoCAD", "Revit", "Coordination"], tools: ["AutoCAD", "Revit", "Microsoft Office"], coverAlt: "Illustration technique d’un plan électrique coordonné avec un chantier", imageType: "technical-illustration", featured: true },
  { slug: "fibre-optique-tests", title: "Fibre optique, Link Test et OTDR", type: "Expérience professionnelle", domain: "Fibre optique", pillar: "terrain", year: "Expérience professionnelle", summary: "Installation de fibre optique et utilisation de tests pour contrôler une liaison et orienter un diagnostic.", context: "Pratique déclarée dans le parcours professionnel en télécommunications et infrastructures.", objective: "Vérifier qu’une liaison correspond aux attentes et repérer une anomalie de manière structurée.", role: "Intervenant technique sur l’installation et le contrôle de liaisons.", work: ["Installation de fibre optique", "Contrôle par Link Test", "Mesures et lecture de traces OTDR", "Communication des observations"], challenges: "Distinguer un symptôme, une mesure et la cause probable sans tirer de conclusion trop rapide.", solution: "Comparer les résultats, vérifier les connexions et documenter les mesures utiles.", result: "Une base pratique en installation, mesure et diagnostic de liaisons fibre.", limitations: "Les détails liés aux sites et aux clients ne sont pas publiés.", skills: ["Fibre optique", "OTDR", "Link Test", "Diagnostic"], tools: ["OTDR", "Testeur de liaison", "Outillage fibre"], coverAlt: "Illustration technique d’une liaison fibre optique contrôlée par un appareil OTDR", imageType: "technical-illustration", featured: false },
  { slug: "laboratoire-proxmox-ve", title: "Laboratoire Proxmox VE", type: "Laboratoire d’apprentissage", domain: "Virtualisation", pillar: "informatique", year: "2026", summary: "Déploiement d’un hyperviseur Proxmox VE, mise à niveau contrôlée et migration de charges Windows de laboratoire.", context: "Environnement personnel pour comprendre Proxmox, ses réseaux, son stockage et le cycle de vie des machines virtuelles.", objective: "Comprendre le cycle de vie d’un hyperviseur, ses réseaux, son stockage et la migration de machines virtuelles.", role: "Conception, exécution, diagnostic et documentation du laboratoire.", work: ["Installation imbriquée pour l’apprentissage", "Configuration du réseau de gestion", "Mise à niveau et contrôle des services", "Import et validation d’images Windows"], challenges: "La virtualisation imbriquée, l’UEFI et les ressources disponibles ont demandé plusieurs diagnostics.", solution: "Procéder par étapes courtes, conserver des retours arrière et valider chaque couche après modification.", result: "Un nœud Proxmox opérationnel, mis à jour et capable d’héberger les machines du laboratoire.", limitations: "La plateforme fonctionne actuellement en virtualisation imbriquée; un hôte physique reste l’objectif futur.", skills: ["Proxmox VE", "QEMU/KVM", "Réseau", "Stockage"], tools: ["Proxmox VE 9", "PowerShell", "qemu-img", "Git"], coverAlt: "Illustration technique d’un nœud Proxmox et de ses machines virtuelles", imageType: "technical-illustration", featured: true },
  { slug: "active-directory-cruzlab", title: "Domaine Active Directory de laboratoire", type: "Laboratoire d’apprentissage", domain: "Systèmes", pillar: "informatique", year: "2026", summary: "Installation de Windows Server, création d’un domaine, DNS, utilisateurs, groupes et première structure d’accès AGDLP.", context: "Laboratoire personnel isolé pour pratiquer les fondations d’un environnement Microsoft.", objective: "Comprendre le rôle du domaine, de DNS, des unités d’organisation et des groupes de sécurité.", role: "Installation, configuration, validation et documentation.", work: ["Préparation de Windows Server", "Promotion du premier contrôleur de domaine", "Validation d’AD DS, DNS et Netlogon", "Création d’utilisateurs, d’OU et de groupes"], challenges: "Distinguer les rôles de chaque service et valider les dépendances sans confondre installation et compréhension.", solution: "Utiliser des noms cohérents et vérifier l’annuaire avec les outils graphiques et PowerShell.", result: "Un domaine de laboratoire fonctionnel avec résolution DNS et une première organisation basée sur les groupes.", limitations: "DHCP, GPO avancées, sauvegarde et second contrôleur de domaine restent des étapes d’apprentissage.", skills: ["Windows Server", "AD DS", "DNS", "AGDLP"], tools: ["Windows Server 2025", "Server Manager", "PowerShell"], coverAlt: "Illustration technique d’un domaine Active Directory avec utilisateurs et groupes", imageType: "technical-illustration", featured: false },
  { slug: "diagnostic-informatique", title: "Diagnostic et remise en service d’ordinateurs", type: "Expérience professionnelle", domain: "Informatique", pillar: "informatique", year: "2013–2015", summary: "Diagnostic hardware et software, réparation, installation et accompagnement d’utilisateurs sur des ordinateurs portables.", context: "Expérience professionnelle chez Toshiba Portugal puis missions de dépannage informatique en Suisse.", objective: "Identifier la cause d’un dysfonctionnement et remettre l’équipement en service de manière compréhensible pour l’utilisateur.", role: "Informaticien puis intervenant en dépannage informatique.", work: ["Diagnostic de pannes", "Remplacement de composants", "Réinstallation de systèmes et logiciels", "Mise en service et information à la clientèle"], challenges: "Passer du symptôme exprimé par l’utilisateur à une cause technique vérifiable.", solution: "Questionner, reproduire, isoler, corriger puis tester le fonctionnement après intervention.", result: "Une première expérience professionnelle solide du support, du matériel et de la relation utilisateur.", skills: ["Diagnostic", "Hardware", "Windows & macOS", "Support"], tools: ["Outils de diagnostic", "Windows", "macOS"], coverAlt: "Illustration technique d’un ordinateur portable en cours de diagnostic", imageType: "technical-illustration", featured: false },
  { slug: "raspberry-pi-services", title: "Services personnels sur Raspberry Pi", type: "Projet personnel", domain: "Auto-hébergement", pillar: "informatique", year: "Projet personnel", summary: "Expérimentation de Plex et Nextcloud avec accès SSH et configuration réseau domestique.", context: "Projet personnel pour explorer Linux, le réseau et l’auto-hébergement.", objective: "Comprendre comment installer, administrer et dépanner un service simple sur un petit serveur.", role: "Conception, installation et maintenance personnelle.", work: ["Installation de services", "Configuration d’une adresse IP fixe", "Administration à distance avec SSH", "Dépannage de la connectivité"], challenges: "Maintenir des services avec des ressources matérielles limitées.", solution: "Procéder par service, documenter les paramètres et tester localement avant toute exposition réseau.", result: "Une première pratique concrète de Linux, du réseau et de l’auto-hébergement.", skills: ["Linux", "Raspberry Pi", "SSH", "Réseau"], tools: ["Raspberry Pi", "Plex", "Nextcloud"], coverAlt: "Illustration technique d’un Raspberry Pi hébergeant des services personnels", imageType: "technical-illustration", featured: false },
  { slug: "domotique-maison", title: "Intégrations domotiques personnelles", type: "Projet personnel", domain: "Domotique", pillar: "informatique", year: "Projet personnel", summary: "Intégration d’éclairages, capteurs, thermostats et caméras dans un environnement domestique.", context: "Projet personnel d’expérimentation avec Home Assistant, Philips Hue, eWeLink, SmartThings, Wi-Fi et Zigbee.", objective: "Centraliser des équipements hétérogènes et créer des scénarios simples et compréhensibles.", role: "Installation, intégration et dépannage dans un cadre privé.", work: ["Association d’équipements", "Création de scénarios", "Diagnostic Wi-Fi et Zigbee", "Organisation des appareils"], challenges: "Faire communiquer des appareils utilisant des plateformes et protocoles différents.", solution: "Intégrer progressivement, nommer clairement et tester chaque automatisation séparément.", result: "Une pratique personnelle de l’intégration, des réseaux domestiques et de l’automatisation.", limitations: "Le projet reste centré sur les usages et les équipements de mon domicile.", skills: ["Home Assistant", "Zigbee", "Wi-Fi", "Automatisation"], tools: ["Home Assistant", "Philips Hue", "eWeLink", "SmartThings"], coverAlt: "Illustration technique d’un réseau domotique avec capteurs et éclairage", imageType: "technical-illustration", featured: false },
];

export const formations = [
  { title: "Planificateur-électricien CFC", institution: "Connect Groupe E", period: "2021–2023", status: "Diplôme terminé", category: "Planification", description: "Formation duale axée sur la planification, la coordination et la documentation d’installations électriques.", skills: ["Plans", "Coordination", "Documentation"] },
  { title: "Installateur-électricien CFC", institution: "Connect Groupe E", period: "2017–2021", status: "Diplôme terminé", category: "Électricité", description: "Formation pratique et théorique en installations électriques, sécurité et exécution sur le terrain.", skills: ["Installation", "Sécurité", "Contrôle"] },
  { title: "Technicien en gestion des équipements informatiques", institution: "INETE, Lisbonne", period: "2010–2013", status: "Diplôme reconnu par le SEFRI", category: "Informatique", description: "Diplôme professionnel obtenu au Portugal et reconnu en Suisse par le SEFRI au niveau CFC, consacré aux systèmes informatiques, au matériel et au support.", skills: ["Systèmes", "Hardware", "Support"] },
  { title: "Systèmes, réseaux et administration", institution: "Laboratoire personnel documenté", period: "2026–en cours", status: "Approfondissement actuel", category: "Systèmes et réseaux", description: "Pratique progressive de Windows Server, Active Directory, DNS, PowerShell, Proxmox VE et postes clients.", skills: ["Windows Server", "Réseau", "Virtualisation"] },
];

export const experiences = [
  { period: "2024–aujourd’hui", role: "Technicien en infrastructures industrielles / planificateur-électricien", company: "Connect Groupe E", domain: "Infrastructures" },
  { period: "2023", role: "Chef de projet et planificateur-électricien", company: "RBM Électricité", domain: "Planification" },
  { period: "2017–2023", role: "Technicien en électronique, installateur puis planificateur-électricien", company: "Missions et formations en Suisse romande", domain: "Terrain & évolution" },
  { period: "2013–2015", role: "Informaticien puis dépannage de systèmes informatiques", company: "Toshiba Portugal et mission en Suisse", domain: "Informatique" },
  { period: "2010–2013", role: "Formation en gestion des équipements informatiques", company: "INETE, Lisbonne", domain: "Fondations IT" },
];

export const trades = [
  { id: "infrastructure", title: "Technicien en infrastructures", intro: "Intervenir sur des installations techniques en reliant sécurité, exécution, contrôle et documentation.", skills: ["Infrastructures industrielles", "Électricité", "Fibre optique", "Diagnostic"], related: ["infrastructures-industrielles", "fibre-optique-tests"] },
  { id: "planification", title: "Planificateur-électricien", intro: "Préparer, coordonner et documenter une solution technique afin qu’elle reste compréhensible du plan au chantier.", skills: ["Planification", "AutoCAD", "Revit", "Coordination"], related: ["planification-electrique"] },
  { id: "gestion-projet", title: "Chef de projet technique", intro: "Organiser les informations, suivre les contraintes et maintenir un lien clair entre les intervenants.", skills: ["Organisation", "Suivi", "Communication", "Documentation"], related: ["planification-electrique", "infrastructures-industrielles"] },
  { id: "support-it", title: "Support informatique", intro: "Passer d’un symptôme utilisateur à un diagnostic vérifiable, puis remettre le poste en service et expliquer la solution.", skills: ["Diagnostic", "Windows", "Matériel", "Communication"], related: ["diagnostic-informatique", "active-directory-cruzlab"] },
  { id: "systemes", title: "Administration systèmes junior", intro: "Approfondissement actuel des systèmes Microsoft, des réseaux et de la virtualisation dans un laboratoire personnel.", skills: ["Windows Server", "Active Directory", "PowerShell", "Proxmox VE"], related: ["laboratoire-proxmox-ve", "active-directory-cruzlab"] },
];
