export type NoteStatus = "published" | "draft";
export type NoteLevel = "Fondamentaux" | "Intermédiaire" | "En approfondissement";
export type NoteType = "Repère personnel" | "Retour d’expérience" | "Note d’apprentissage" | "Explication générale" | "Comparaison" | "Méthode de diagnostic";

export type TechnicalNote = {
  title: string; slug: string; category: string; type: NoteType; summary: string;
  createdAt: string; updatedAt: string; reading: string; level: NoteLevel;
  illustration: "electricite" | "planification" | "fibre" | "diagnostic" | "systemes" | "virtualisation" | "reseaux" | "domotique";
  introduction: string; sections: { title: string; text: string }[];
  keyPoints: string[]; tools: string[]; relatedProject?: string; sources: string[]; status: NoteStatus;
};

const common = { createdAt: "2026-07-28", updatedAt: "2026-07-28" };

export const technicalNotes: TechnicalNote[] = [
  { ...common, slug:"dns-a-quoi-sert-il", title:"DNS : à quoi sert-il ?", category:"Systèmes", type:"Note d’apprentissage", summary:"Le service qui relie les noms faciles à retenir aux adresses utilisées par le réseau.", reading:"4 min", level:"Fondamentaux", illustration:"systemes", introduction:"Dans mon laboratoire Active Directory, DNS est rapidement devenu le fil conducteur : sans résolution de noms correcte, le domaine ne fonctionne pas comme prévu.", sections:[{title:"Ce que c’est",text:"DNS traduit un nom, comme lab-dc01.cruzlab.test, en adresse IP. Il publie aussi les services nécessaires pour qu’un poste trouve un contrôleur de domaine."},{title:"À quoi cela sert",text:"Il évite de mémoriser des adresses et permet aux services de se découvrir. Dans Active Directory, les enregistrements SRV indiquent notamment où joindre LDAP et le contrôleur de domaine."},{title:"Mon repère de diagnostic",text:"Je vérifie l’adresse IP, le serveur DNS configuré, puis la résolution du nom. Cette séquence évite d’accuser trop vite le réseau ou le domaine."}],keyPoints:["Un nom et une adresse IP ne sont pas la même chose","Active Directory dépend fortement de DNS","Tester du plus simple au plus spécifique"],tools:["Resolve-DnsName","nslookup","ipconfig /all"],relatedProject:"active-directory-cruzlab",sources:["Microsoft Learn — Vue d’ensemble de DNS","RFC 1034 — Domain Names"],status:"published" },
  { ...common, slug:"dhcp-configuration-reseau", title:"DHCP : comment un poste reçoit sa configuration", category:"Réseaux", type:"Explication générale", summary:"Comprendre l’attribution automatique d’une adresse IP, d’une passerelle et de serveurs DNS.", reading:"4 min", level:"Fondamentaux", illustration:"reseaux", introduction:"Cette note m’aide à distinguer ce qui est configuré manuellement de ce qu’un serveur peut distribuer automatiquement aux clients.", sections:[{title:"Le rôle de DHCP",text:"DHCP fournit une configuration réseau à un client : adresse IP, masque, passerelle et serveurs DNS. L’administrateur définit une plage et des options adaptées au réseau."},{title:"Le déroulement",text:"Le client cherche un serveur, reçoit une proposition, demande l’adresse proposée puis obtient une confirmation. Ce cycle est souvent résumé par DORA."},{title:"Ce que je retiens",text:"Un serveur important garde généralement une adresse fixe. Les postes clients peuvent recevoir une adresse dans une plage contrôlée."}],keyPoints:["Évite les configurations manuelles répétitives","Les baux ont une durée","Les exclusions protègent les adresses réservées"],tools:["ipconfig /all","Get-NetIPConfiguration"],sources:["Microsoft Learn — DHCP overview"],status:"published" },
  { ...common, slug:"active-directory-role-general", title:"Active Directory : rôle général", category:"Systèmes", type:"Note d’apprentissage", summary:"Centraliser les identités, les ordinateurs et les règles d’un environnement Windows.", reading:"5 min", level:"Fondamentaux", illustration:"systemes", introduction:"J’ai créé mon premier domaine cruzlab.test pour relier concrètement les notions d’utilisateur, de groupe, d’OU, de DNS et de GPO.", sections:[{title:"Ce que centralise l’annuaire",text:"AD DS conserve les objets du domaine et permet leur authentification. Les administrateurs organisent les objets et délèguent les droits sans gérer chaque poste séparément."},{title:"Le contrôleur de domaine",text:"Le contrôleur de domaine héberge l’annuaire et répond aux demandes d’authentification. Dans mon laboratoire, LAB-DC01 héberge aussi DNS."},{title:"Ce que j’ai pratiqué",text:"Installation de Windows Server, promotion d’un nouveau domaine, création d’utilisateurs, d’OU et de groupes, puis validation avec PowerShell."}],keyPoints:["Le domaine donne un cadre commun","DNS permet de localiser ses services","Les groupes facilitent une gestion durable des accès"],tools:["Server Manager","Active Directory Users and Computers","PowerShell"],relatedProject:"active-directory-cruzlab",sources:["Microsoft Learn — Active Directory Domain Services overview"],status:"published" },
  { ...common, slug:"agdpl-explique-simplement", title:"AGDLP expliqué simplement", category:"Systèmes", type:"Repère personnel", summary:"Une méthode pour attribuer des droits sans lier directement chaque utilisateur à chaque ressource.", reading:"4 min", level:"Intermédiaire", illustration:"systemes", introduction:"La confusion que je voulais éviter était de mélanger les personnes, leurs rôles et les permissions sur les dossiers.", sections:[{title:"La chaîne",text:"Accounts entrent dans des Global Groups. Ces groupes rejoignent des Domain Local Groups. Les Permissions sont attribuées aux groupes locaux."},{title:"Pourquoi cette structure aide",text:"Un changement de poste se traite dans le groupe de rôle. Un changement d’accès se traite dans le groupe lié à la ressource."},{title:"Pratique du laboratoire",text:"J’ai créé GG_IT_Support, ajouté un utilisateur, puis placé ce groupe dans DL_FS_Helpdesk_RW et validé l’appartenance avec PowerShell."}],keyPoints:["A → GG → DL → P","Séparer rôle et accès","Toujours valider l’appartenance après modification"],tools:["Active Directory Users and Computers","Get-ADGroup","Get-ADUser"],relatedProject:"active-directory-cruzlab",sources:["Microsoft Learn — Active Directory security groups"],status:"published" },
  { ...common, slug:"hyperviseur-role", title:"Qu’est-ce qu’un hyperviseur ?", category:"Virtualisation", type:"Explication générale", summary:"La couche qui partage les ressources physiques entre plusieurs machines virtuelles.", reading:"3 min", level:"Fondamentaux", illustration:"virtualisation", introduction:"Comprendre cette couche m’a aidé à distinguer Hyper-V, Proxmox VE et les systèmes invités qu’ils hébergent.", sections:[{title:"Le principe",text:"L’hyperviseur attribue processeur, mémoire, stockage et réseau virtuel à chaque VM tout en maintenant leur isolation."},{title:"Type 1 et type 2",text:"Un hyperviseur de type 1 fonctionne directement sur le matériel. Un type 2 s’exécute au-dessus d’un système d’exploitation hôte."},{title:"Ce que je retiens",text:"L’hyperviseur héberge les machines. Il ne remplace pas Windows Server, qui fournit des rôles comme AD DS, DNS ou DHCP."}],keyPoints:["Héberge plusieurs systèmes","Isole les charges","Ne remplace pas les services des systèmes invités"],tools:["Proxmox VE","Hyper-V"],relatedProject:"laboratoire-proxmox-ve",sources:["Proxmox VE Administration Guide","Microsoft Learn — Hyper-V overview"],status:"published" },
  { ...common, slug:"proxmox-hyperv-virtualbox", title:"Proxmox, Hyper-V et VirtualBox", category:"Virtualisation", type:"Comparaison", summary:"Trois plateformes utiles, mais pensées pour des contextes différents.", reading:"5 min", level:"Fondamentaux", illustration:"virtualisation", introduction:"J’ai commencé avec Hyper-V, puis construit un laboratoire Proxmox imbriqué pour comparer les approches et préparer une future migration physique.", sections:[{title:"Hyper-V",text:"Intégré aux éditions compatibles de Windows, il convient bien aux laboratoires Microsoft et à la gestion de VM depuis un poste Windows."},{title:"Proxmox VE",text:"Plateforme de virtualisation basée sur Debian, administrée principalement depuis une interface web et adaptée à un hôte dédié."},{title:"VirtualBox",text:"Application multiplateforme pratique pour des essais locaux. Son positionnement diffère d’une plateforme dédiée à un serveur de virtualisation."}],keyPoints:["Choisir selon l’hôte et l’objectif","Comparer réseau, stockage et exploitation","La virtualisation imbriquée a des limites"],tools:["Proxmox VE","Hyper-V","VirtualBox"],relatedProject:"laboratoire-proxmox-ve",sources:["Proxmox VE documentation","Microsoft Learn — Hyper-V","Oracle VirtualBox User Manual"],status:"published" },
  { ...common, slug:"snapshot-sauvegarde-retour", title:"Snapshot, sauvegarde et retour arrière", category:"Virtualisation", type:"Comparaison", summary:"Un snapshot facilite un retour rapide, mais ne remplace pas une sauvegarde indépendante.", reading:"4 min", level:"Fondamentaux", illustration:"virtualisation", introduction:"Les checkpoints Hyper-V m’ont montré qu’un retour arrière est pratique, mais qu’une longue chaîne de disques différenciés complique la migration.", sections:[{title:"Snapshot",text:"Il capture un état logique et crée souvent une dépendance avec un disque parent. Il est utile avant une modification courte et contrôlée."},{title:"Sauvegarde",text:"Une sauvegarde doit pouvoir être restaurée même si le stockage principal est perdu. Elle suit une politique de rétention et de vérification."},{title:"Bonne habitude",text:"Nommer le point de retour, documenter sa raison, puis le supprimer ou le consolider lorsqu’il n’est plus nécessaire."}],keyPoints:["Snapshot ≠ sauvegarde","Éviter les chaînes oubliées","Tester les restaurations"],tools:["Hyper-V checkpoints","Proxmox snapshots","qm snapshot"],relatedProject:"laboratoire-proxmox-ve",sources:["Proxmox VE Administration Guide","Microsoft Learn — Hyper-V checkpoints"],status:"published" },
  { ...common, slug:"ip-masque-passerelle-dns", title:"Adresse IP, masque, passerelle et DNS", category:"Réseaux", type:"Repère personnel", summary:"Quatre valeurs à distinguer avant de commencer un diagnostic réseau.", reading:"4 min", level:"Fondamentaux", illustration:"reseaux", introduction:"Dans mon laboratoire 10.10.10.0/24, ces quatre éléments ont servi à relier l’hôte, Proxmox et les machines invitées.", sections:[{title:"Adresse et masque",text:"L’adresse identifie une interface. Le masque indique quelle partie représente le réseau local et quelles adresses sont directement joignables."},{title:"Passerelle",text:"La passerelle reçoit le trafic destiné à un autre réseau. Dans le laboratoire, 10.10.10.1 assure ce rôle vers le NAT de l’hôte."},{title:"DNS",text:"Le serveur DNS traduit les noms. Un ping vers une IP peut fonctionner alors qu’une résolution de nom échoue."}],keyPoints:["Même sous-réseau : communication directe","Autre réseau : passerelle","Nom : résolution DNS"],tools:["ipconfig","ping","nslookup","Get-NetIPConfiguration"],sources:["Microsoft Learn — TCP/IP fundamentals"],status:"published" },
  { ...common, slug:"diagnostic-reseau-premiere-methode", title:"Première méthode de diagnostic réseau", category:"Réseaux", type:"Méthode de diagnostic", summary:"Valider chaque couche dans un ordre simple au lieu de changer plusieurs paramètres à la fois.", reading:"5 min", level:"Fondamentaux", illustration:"reseaux", introduction:"Cette méthode vient directement des erreurs rencontrées pendant la construction du réseau isolé du laboratoire.", sections:[{title:"1. Observer",text:"Lire l’état de l’adaptateur, l’adresse, le masque, la passerelle et DNS. Une adresse 169.254.x.x indique souvent qu’aucune configuration IPv4 utile n’a été obtenue."},{title:"2. Tester par étapes",text:"Tester la pile locale, une adresse du même réseau, la passerelle, une adresse Internet puis un nom DNS."},{title:"3. Corriger une seule chose",text:"Après chaque modification, refaire le test correspondant. Cela rend la cause et la correction compréhensibles."}],keyPoints:["Observer avant de modifier","IP avant DNS","Une correction, un test"],tools:["ping","ipconfig","nslookup","tracert"],sources:["Microsoft Learn — Troubleshoot TCP/IP connectivity"],status:"published" },
  { ...common, slug:"diagnostiquer-sans-conclure", title:"Diagnostiquer sans sauter aux conclusions", category:"Diagnostic", type:"Méthode de diagnostic", summary:"Passer d’un symptôme à une cause vérifiable, puis confirmer la remise en service.", reading:"5 min", level:"Fondamentaux", illustration:"diagnostic", introduction:"C’est le fil conducteur que je retrouve entre le dépannage informatique, le terrain et les laboratoires systèmes.", sections:[{title:"Clarifier le symptôme",text:"Demander ce qui se passe, depuis quand et dans quelles conditions. Reproduire le problème si cela peut être fait sans risque."},{title:"Isoler",text:"Tester une hypothèse à la fois, du plus simple au plus spécifique. Éviter de remplacer plusieurs éléments en même temps."},{title:"Valider et expliquer",text:"Après la correction, refaire le scénario initial et expliquer ce qui a été observé, changé et vérifié."}],keyPoints:["Symptôme n’est pas cause","Une hypothèse à la fois","Tester après réparation"],tools:["Journal de tests","Outils de diagnostic"],relatedProject:"diagnostic-informatique",sources:["Retour d’expérience général de Daniel Cruz"],status:"published" },
  { ...common, slug:"link-test-et-otdr", title:"Link Test et OTDR : deux contrôles différents", category:"Fibre optique", type:"Comparaison", summary:"Valider une liaison et localiser ses événements ne répondent pas exactement à la même question.", reading:"5 min", level:"Intermédiaire", illustration:"fibre", introduction:"Cette distinction m’aide à choisir la bonne mesure et à ne pas interpréter une trace sans son contexte.", sections:[{title:"Link Test",text:"Il vérifie les performances globales d’une liaison selon une méthode et des limites définies."},{title:"OTDR",text:"Il envoie une impulsion et observe la lumière rétrodiffusée pour représenter les événements et pertes le long de la fibre."},{title:"Documenter",text:"Conserver les paramètres, le sens de mesure et les résultats utiles permet une comparaison fiable."}],keyPoints:["Deux objectifs différents","Nettoyer et vérifier les connecteurs","Interpréter avec les paramètres de test"],tools:["Testeur de liaison","OTDR","Kit de nettoyage"],relatedProject:"fibre-optique-tests",sources:["Principes généraux de mesure fibre; procédures fabricant à respecter"],status:"published" },
  { ...common, slug:"autocad-revit-approches", title:"AutoCAD et Revit : deux approches complémentaires", category:"Planification", type:"Comparaison", summary:"Le dessin 2D et la modélisation orientée objet répondent à des besoins proches avec des méthodes différentes.", reading:"4 min", level:"Fondamentaux", illustration:"planification", introduction:"J’ai utilisé ces outils dans mon parcours de planificateur-électricien. Cette note garde un repère simple sur leur logique.", sections:[{title:"AutoCAD",text:"Il offre un contrôle direct du dessin et reste très efficace pour produire, corriger et échanger des plans 2D."},{title:"Revit",text:"Il organise le projet autour d’objets et de vues coordonnées dans un modèle. Les informations sont liées entre elles."},{title:"Le choix",text:"Le bon outil dépend du projet, du niveau de coordination attendu et des méthodes de l’équipe."}],keyPoints:["Dessin et modèle ne se structurent pas pareil","La qualité des données reste essentielle","Le format d’échange fait partie du travail"],tools:["AutoCAD","Revit"],relatedProject:"planification-electrique",sources:["Autodesk Help — AutoCAD et Revit"],status:"published" },
  { ...common, slug:"documenter-une-modification", title:"Pourquoi documenter une modification", category:"Planification", type:"Retour d’expérience", summary:"Une décision claire aujourd’hui évite une recherche et une reprise demain.", reading:"3 min", level:"Fondamentaux", illustration:"planification", introduction:"Le terrain et la planification m’ont appris qu’une modification non transmise devient rapidement une nouvelle source d’erreur.", sections:[{title:"Garder une trace",text:"La documentation relie la demande, la décision, la date et l’élément concerné."},{title:"Adapter au destinataire",text:"Une information utile au chantier n’a pas toujours la même forme qu’une information destinée à la maintenance ou au suivi de projet."},{title:"Fermer la boucle",text:"Après la réalisation, le document doit refléter la situation réellement exécutée selon le processus du projet."}],keyPoints:["Une source de vérité claire","Version et date visibles","Le plan doit suivre la réalité"],tools:["Plans techniques","Liste de points","Compte rendu"],relatedProject:"planification-electrique",sources:["Retour d’expérience général de planification"],status:"published" },
  { ...common, slug:"tgbt-role-general", title:"À quoi sert un TGBT ?", category:"Électricité", type:"Explication générale", summary:"Le point central qui reçoit, répartit, protège et permet de superviser une distribution électrique importante.", reading:"4 min", level:"Fondamentaux", illustration:"electricite", introduction:"Cette note reste volontairement générale : elle sert à garder la vue d’ensemble d’une distribution, pas à remplacer une procédure d’intervention.", sections:[{title:"Le rôle général",text:"Un tableau général basse tension reçoit l’énergie et la distribue vers plusieurs départs. Il regroupe des fonctions de coupure, protection, mesure et parfois de supervision."},{title:"Lire l’ensemble",text:"On part de la source, puis on suit les jeux de barres, protections et départs jusqu’aux équipements alimentés."},{title:"Point d’attention",text:"Toute intervention dépend du schéma, des procédures du site et des règles de sécurité applicables. Cette note ne décrit aucune manœuvre."}],keyPoints:["Distribution centrale","Protection et séparation des départs","Toujours travailler avec les documents et procédures applicables"],tools:["Schéma unifilaire","Repérage technique"],relatedProject:"infrastructures-industrielles",sources:["Repère général issu du parcours professionnel; aucune prescription de sécurité publiée"],status:"published" },
  { ...common, slug:"raspberry-pi-petit-serveur", title:"Raspberry Pi comme petit serveur", category:"Domotique", type:"Retour d’expérience", summary:"Un support compact pour découvrir Linux, SSH, le réseau et quelques services personnels.", reading:"4 min", level:"Fondamentaux", illustration:"domotique", introduction:"Mon Raspberry Pi m’a servi de terrain d’essai pour Plex, Nextcloud, une adresse IP fixe et l’administration à distance.", sections:[{title:"Pourquoi ce format",text:"Il consomme peu, reste discret et suffit pour expérimenter des services simples dans un réseau domestique."},{title:"Les premières briques",text:"Système à jour, compte administrateur protégé, adresse réseau cohérente, SSH et sauvegarde de la configuration."},{title:"Les limites",text:"Le stockage, la mémoire et les performances restent modestes. Il faut choisir les services et surveiller les ressources."}],keyPoints:["Commencer par un service","Sécuriser l’accès distant","Documenter l’adresse et les sauvegardes"],tools:["Raspberry Pi","Linux","SSH","Plex","Nextcloud"],relatedProject:"raspberry-pi-services",sources:["Raspberry Pi Documentation"],status:"published" },
  { ...common, slug:"wifi-ou-zigbee", title:"Wi-Fi ou Zigbee ?", category:"Domotique", type:"Comparaison", summary:"Deux manières de connecter des appareils domestiques, avec des compromis différents.", reading:"4 min", level:"Fondamentaux", illustration:"domotique", introduction:"Mes intégrations personnelles m’ont montré qu’un appareil facile à connecter n’est pas toujours le plus simple à maintenir dans un ensemble.", sections:[{title:"Wi-Fi",text:"L’appareil rejoint le réseau IP existant. Cela simplifie parfois l’installation mais augmente le nombre d’équipements sur le Wi-Fi."},{title:"Zigbee",text:"Les appareils utilisent un réseau maillé distinct autour d’un coordinateur. Les équipements alimentés peuvent relayer les messages."},{title:"Choisir",text:"Je regarde l’autonomie, la portée, l’écosystème, le fonctionnement local et la facilité de dépannage."}],keyPoints:["Deux réseaux différents","Le coordinateur Zigbee est central","Privilégier une organisation claire des appareils"],tools:["Home Assistant","Philips Hue","SmartThings"],relatedProject:"domotique-maison",sources:["Connectivity Standards Alliance — Zigbee overview"],status:"published" },
  ...([
    ["couleurs-conducteurs-suisse","Couleurs des conducteurs électriques en Suisse","Électricité","electricite"],
    ["securite-electrique-suisse","Règles de sécurité électrique suisses","Électricité","electricite"],
    ["eclairage-secours","Éclairage de secours : principe général","Électricité","electricite"],
    ["installations-photovoltaiques","Introduction aux installations photovoltaïques","Électricité","electricite"],
    ["bim-modelisation-3d","BIM et modélisation 3D : principes généraux","Planification","planification"],
    ["fibre-monomode-multimode","Fibre monomode et multimode","Fibre optique","fibre"],
    ["uefi-bios-demarrage","UEFI, BIOS et séquence de démarrage","Diagnostic","diagnostic"],
    ["gpo-principe-general","GPO : principe général","Systèmes","systemes"],
    ["droits-ntfs-partages","Droits NTFS et partages réseau","Systèmes","systemes"],
    ["virtualisation-imbriquee","Virtualisation imbriquée : utilité et limites","Virtualisation","virtualisation"],
    ["switch-routeur-point-acces","Switch, routeur et point d’accès","Réseaux","reseaux"],
    ["ssh-administration-distance","SSH : administration à distance","Réseaux","reseaux"],
    ["home-assistant-role","Rôle de Home Assistant","Domotique","domotique"],
  ] as Array<[string, string, string, TechnicalNote["illustration"]]>).map(([slug,title,category,illustration]) => ({ ...common, slug, title, category, illustration, type:"Note d’apprentissage" as NoteType, summary:"Sujet préparé pour une prochaine session de documentation.", reading:"—", level:"En approfondissement" as NoteLevel, introduction:"", sections:[], keyPoints:[], tools:[], sources:[], status:"draft" as NoteStatus })),
];

export const publishedNotes = technicalNotes.filter((note) => note.status === "published");
